# Generated by Django 4.2 on 2023-04-21 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_desk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.TextField(default='Комментариев нет', verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='task',
            name='dep',
            field=models.CharField(default='Отсутствует', max_length=24, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='task',
            name='fio',
            field=models.CharField(default='???', max_length=56, verbose_name='ФИО пользователя'),
        ),
        migrations.AlterField(
            model_name='task',
            name='pc_name',
            field=models.CharField(default='???', max_length=24, verbose_name='имя компьютера'),
        ),
        migrations.AlterField(
            model_name='task',
            name='phone',
            field=models.CharField(default='Отсутствует', max_length=24, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False, verbose_name='выполнено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время дата'),
        ),
    ]
