# Generated by Django 4.2 on 2023-04-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56, verbose_name='название заявки')),
                ('text', models.TextField(verbose_name='текст заявки')),
                ('time_date', models.DateTimeField(verbose_name='время дата')),
                ('status', models.BooleanField(verbose_name='выполнено')),
                ('comment', models.TextField(verbose_name='комментарий')),
                ('pc_ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('pc_name', models.CharField(max_length=24, verbose_name='имя компьютера')),
                ('fio', models.CharField(max_length=56, verbose_name='ФИО пользователя')),
                ('phone', models.CharField(max_length=24, verbose_name='Номер телефона')),
                ('dep', models.CharField(max_length=24, verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_ip', models.CharField(max_length=15, verbose_name='IP адрес')),
                ('pc_name', models.CharField(max_length=24, verbose_name='имя компьютера')),
                ('fio', models.CharField(max_length=56, verbose_name='ФИО пользователя')),
                ('phone', models.CharField(max_length=24, verbose_name='Номер телефона')),
                ('dep', models.CharField(max_length=24, verbose_name='Отдел')),
                ('admin', models.BooleanField(verbose_name='Право доступа')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
    ]
